version: 1.0.{build}
branches:
  only:
  - master
image: Previous Visual Studio 2017
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
environment:
  CODECOV_TOKEN: 93f1ba74-2bc4-4b01-8e9e-3a3c97825e91
build_script:
- cmd: >-
    cd src
    cd AspNetCore.AutoHealthCheck
    dotnet build